---
apiVersion: apps/v1
kind: Deployment
metadata:
{{- if hasKey .Values "deployment" }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- else }}
  annotations: {}
{{- end }}
{{- end }}
  labels:
    app: platform
    service: client
  name: client

spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: platform
      service: client
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: platform
        service: client
    spec:
      containers:
      - livenessProbe:
          httpGet:
            path: /api/v3/config
            port: 8080
        env:
        - name: BACKEND_URL
          value: {{ .Values.backend_url }}
        {{- if (.Values.config).ga_key }}
        - name: GA_KEY
          value: {{ .Values.config.ga_key | quote }}
        {{- end }}
        {{- if (.Values.config).google_maps_api_key }}
        - name: GOOGLE_MAPS_API_KEY
          value: {{ .Values.config.google_maps_api_key | quote }}
        {{- end }}
        {{- if (.Values.config).gtm_container_id }}
        - name: GTM_CONTAINER_ID
          value: {{ .Values.config.gtm_container_id | quote }}
        {{- end }}
        {{- if (.Values.config).intercom_appid }}
        - name: INTERCOM_APPID
          value: {{ .Values.config.intercom_appid | quote }}
        {{- end }}
        {{- if ((.Values.config).multisite).domain }}
        - name: MULTISITE_DOMAIN
          value: {{ .Values.config.multisite.domain | quote }}
        {{- end }}
        {{- if ((.Values.config).multisite).api_domain }}
        - name: MULTISITE_API_DOMAIN
          value: {{ .Values.config.multisite.api_domain | quote }}
        {{- end }}
        {{- if (.Values.config.sentry).dsn }}
        - name: SENTRY_DSN
          value: {{ .Values.config.sentry.dsn | quote }}
        {{- end }}
        {{- if (.Values.config.sentry).environment }}
        - name: SENTRY_ENVIRONMENT
          value: {{ .Values.config.sentry.environment | quote }}
        {{- end }}
        {{- if (.Values.config.sentry).debug_mode }}
        - name: SENTRY_DEBUG_MODE
          value: {{ .Values.config.sentry.debug_mode | quote }}
        {{- end }}
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: api
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}
      terminationGracePeriodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    service: client
  name: client
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: platform
    service: client

{{- if .Values.ingress.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- else }}
  annotations: {}
{{- end }}
  name: client
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: client
            port:
              name: http

{{- if .Values.ingress.aliases -}}
{{- range .Values.ingress.aliases }}
  - host: {{ . | quote }}
    http:
      paths:
      - path: /
        backend:
          service:
            name: client
          port:
            name: http
{{- end -}}
{{- end -}}

{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}
