image:
  repository: ushahidi
  name: platform
  tag: latest

config:
  appkey: "SomeRandomKey!!!SomeRandomKey!!!"
  timezone: UTC
  hdx_url: https://data.humdata.org/
  db:
    host: mysql
    port: 3306
    database: ushahidi
    username: ushahidi
    password: ushahidi
  redis:
    host: redis
    port: 6379
  drivers:
    cache: redis
    ratelimiter_cache: redis
    queue: redis
    filesystem: local
    mail: log     # -> e-mail disabled by default
  mail_from:
    address: admin@example.com
    name: "Platform Deployment Admin"
  ## Additional settings provided in .env file, note that this only works for
  ## versions after commit
  ## https://github.com/ushahidi/platform/pull/3986/commits/2e03a09e3e8c4731b2f0ad3298806363c6d076d8
  # dotenv: ""

api:
  replicas: 1
  debug: "False"
  params:
    php_exec_time_limit: 60
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"
  ingress:
    enabled: false
    # annotations:
    # tls:
    # - secretName: domain.example.com
    #   hosts:
    #   - domain.example.com
    host: # domain.example.com

worker:
  replicas: 1
  debug: "False"
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"

# This provides a compatible mysql server, with EPHEMERAL storage.
# Don't rely on it for production.
mysql:
  ## Set to false to disable
  enabled: true
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"

# This provides a compatible redis server, with EPHEMERAL storage.
# Don't rely on it for production.
redis:
  ## Set to false to disable
  enabled: true
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"
