# there is no sensible default for this
# set to something like https://apihost.example.com
backend_url: ""

# other configuration values
config: {}
#  gtm_container_id: 
#  google_maps_api_key:
#  ga_key:
#  intercom_appid:
#  multisite:   # (platform-client-mzima images only)
#    domain:
#    api_domain:

replicas: 1
limits:
  cpu: "1"
  memory: "1Gi"
requests:
  cpu: "10m"
  memory: "64Mi"
# deployment:
#   annotations:
ingress:
  enabled: false
  # annotations:
  # tls:
  # - secretName: domain.example.com
  #   hosts:
  #   - domain.example.com
  host: # domain.example.com

image:
  repository: ushahidi
  name: platform-client
  tag: latest
