---
apiVersion: apps/v1
kind: Deployment
metadata:
{{- if hasKey .Values "deployment" }}
{{- if .Values.deployment.annotations }}
  annotations:
{{ toYaml .Values.deployment.annotations | indent 4 }}
{{- else }}
  annotations: {}
{{- end }}
{{- end }}
  labels:
    app: ussd-engine
    service: botman
  name: ussd-engine

spec:
  minReadySeconds: 5
  progressDeadlineSeconds: 600
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: ussd-engine
      service: botman
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ussd-engine
        service: botman
    spec:
      containers:
      - command:
        - /bin/bash
        - /entrypoint.CES.sh
        - start
        livenessProbe:
          httpGet:
            path: /
            port: 8080
        env:
        - name: APP_KEY
          {{- if .Values.config.appkey }}
          value: {{ .Values.config.appkey | quote }}
          {{ else if .Values.config.appkey_secret }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.config.appkey_secret.name }}
              key: {{ .Values.config.appkey_secret.key }}
          {{ else }}
          value: {{ randAlphaNum 32 | quote }}
          {{- end }}
        - name: APP_DEBUG
          value: {{ .Values.debug | quote }}
        - name: APP_TIMEZONE
          value: {{ .Values.config.timezone }}
        - name: REDIS_HOST
          value: {{ .Values.config.redis.host }}
        - name: REDIS_PORT
          value: {{ .Values.config.redis.port | quote }}
        - name: CACHE_DRIVER
          value: {{ .Values.config.drivers.cache }}
        - name: SESSION_DRIVER
          value: {{ .Values.config.drivers.session }}
        - name: SESSION_LIFETIME
          value: {{ .Values.config.session.lifetime | quote }}
        - name: USHAHIDI_PLATFORM_API_URL
          value: {{ .Values.config.ushahidi_platform_api.url | quote }}
        - name: USHAHIDI_PLATFORM_API_VERSION
          value: {{ .Values.config.ushahidi_platform_api.version | default "5" |quote }}
        {{- if .Values.config.whatsapp.access_token }}
        - name: WHATSAPP_ACCESS_TOKEN
          value: {{ .Values.config.whatsapp.access_token | quote }}
        - name: WHATSAPP_VERIFY_TOKEN
          value: {{ .Values.config.whatsapp.verify_token | quote }}
        {{- end }}
        {{- if .Values.config.ushahidi_platform_geo_api.url  }}
        - name: USHAHIDI_PLATFORM_GEO_API_URL
          value: {{ .Values.config.ushahidi_platform_geo_api.url | quote }}
        - name: USHAHIDI_PLATFORM_GEO_API_VERSION
          value: {{ .Values.config.ushahidi_platform_geo_api.version | default "5" | quote }}
        {{- end }}

        - { name: DOCKERIZE_TIMEOUT, value: 180s }
        - name: DOCKERIZE_WAIT_FOR_redis
          value: "tcp://{{ .Values.config.redis.host }}:{{ .Values.config.redis.port }}"
        - name: PHP_EXEC_TIME_LIMIT
          value: {{ .Values.params.php_exec_time_limit | quote }}
        
        image: {{ .Values.image.repository }}/{{ .Values.image.name }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        name: ussd-engine
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.limits.cpu }}
            memory: {{ .Values.limits.memory }}
          requests:
            cpu: {{ .Values.requests.cpu }}
            memory: {{ .Values.requests.memory }}

        {{- if or .Values.config.settings_file .Values.config.lang_strings_file }}
        volumeMounts:
        {{- if .Values.config.settings_file  }}
        - name: config-settings-file
          mountPath: /var/www/settings.json
          subPath: settings.json
        {{- end }}
        {{- if .Values.config.lang_strings_file  }}
        - name: config-lang-strings-file
          mountPath: /var/www/lang_strings.json
          subPath: lang_strings.json
        {{- end }}
        {{- end }}

      {{- if or .Values.config.settings_file .Values.config.lang_strings_file }}
      volumes:
      {{- if .Values.config.settings_file }}
      - name: config-settings-file
        configMap:
          name: ussd-engine-settings
      {{- end }}
      {{- if .Values.config.lang_strings_file }}
      - name: config-lang-strings-file
        configMap:
          name: ussd-engine-lang-strings
      {{- end }}
      {{- end }}

      terminationGracePeriodSeconds: 15

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ussd-engine
    service: botman
  name: ussd-engine
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: ussd-engine
    service: botman
  type: ClusterIP

{{- if .Values.ingress.enabled }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- if .Values.ingress.annotations }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}
{{- else }}
  annotations: {}
{{- end }}
  name: ussd-engine
spec:
  rules:
  - host: {{ .Values.ingress.host | quote }}
    http:
      paths:
      - path: /
        backend:
          serviceName: ussd-engine
          servicePort: http
{{- if .Values.ingress.tls }}
  tls:
{{ toYaml .Values.ingress.tls | indent 4 }}
{{- end -}}
{{- end }}