image:
  repository: ushahidi
  name: ussd-engine
  tag: latest

config:
  # appkey:
  # appkey_secret:
  #   name:
  #   key:
  timezone: UTC  
  redis:
    host: ussd-engine-redis
    port: 6379
  drivers:
    cache: redis
    session: redis
    mail: log     # -> e-mail disabled by default
  session:
    lifetime: 120

  # The final base url for platform API access will be built as:
  #   {{ ushahidi_platform_api.url }}/api/v{{ ushahidi_platform_api.version }}/
  ushahidi_platform_api:
    url:
    version: 5
    timeout: "2.0"

  # optional different endpoint for geocoding still via platform API
  # ushahidi_platform_geo_api:
  #   url:
  #   version: 5

  # this maps to the settings.json file
  # settings_file:
  #   enabled_languages: []
  #   enabled_surveys: []
  #   when_default_values:
  #     title: ignore
  #     description: ignore
  #     other: ignore

  # this maps to the lang_strings.json file
  # lang_strings_file:
  #   en:
  #     conversation.selectSurvey: Make your pick
  #   es:
  #     conversation.selectSurvey: Elija uno

  # whatsapp:
  #   access_token:
  #   verify_token:

replicas: 1
debug: "False"
params:
  php_exec_time_limit: 60
limits:
  cpu: "1"
  memory: "1Gi"
requests:
  cpu: "10m"
  memory: "64Mi"
# deployment:
#   annotations:
ingress:
  enabled: false
  # annotations:
  # tls:
  # - secretName: domain.example.com
  #   hosts:
  #   - domain.example.com
  host: # domain.example.com

# This provides a compatible redis server, with EPHEMERAL storage.
# Don't rely on it for production.
redis:
  ## Set to false to disable
  enabled: true
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"
