{{- if .Values.redis.enabled }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations: {}
  labels:
    app: platform
    service: redis
  name: redis-ephemeral

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: platform
      service: redis
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: platform
        service: redis
    spec:
      containers:
      - env: []
        {{- with .Values.redis.image }}
        image: {{ empty .repository | ternary "" (print .repository "/") }}{{ .name }}:{{ .tag }}
        {{- end }}
        imagePullPolicy: Always
        name: redis
        ports:
        - containerPort: 6379
          name: mysql
          protocol: TCP
        resources:
          limits:
            cpu: {{ .Values.redis.limits.cpu }}
            memory: {{ .Values.redis.limits.memory }}
          requests:
            cpu: {{ .Values.redis.requests.cpu }}
            memory: {{ .Values.redis.requests.memory }}
      terminationGracePeriodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: platform
    service: redis
  name: redis
spec:
  ports:
  - name: redis
    port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: platform
    service: redis
  type: ClusterIP

{{- end }}
