apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    kind: Ingress
  ## JSON pointer spec: "~1" translates to "/" character in a dictionary key
  patch: |-
    [
      {"op": "add",
      "path": "/metadata/annotations/ingress.kubernetes.io~1ssl-redirect",
      "value": "true"},
      {"op": "add",
      "path": "/metadata/annotations/ingress.kubernetes.io~1ssl-proxy-headers",
      "value": "X-Forwarded-Proto: https"}
    ]
