image:
  repository: ushahidi
  name: platform
  tag: latest

config:
  # appkey:
  # appkey_secret:
  #   name:
  #   key:
  timezone: UTC
  hdx_url: https://data.humdata.org/
  db:
    host: mysql
    port: 3306
    database: ushahidi
    username: ushahidi
    password: ushahidi
    # password_secret:
    #   name:
    #   key:
  redis:
    host: redis
    port: 6379
  drivers:
    cache: redis
    ratelimiter_cache: redis
    queue: redis
    filesystem: local
    mail: log     # -> e-mail disabled by default
  mail_from:
    address: admin@example.com
    name: "Platform Deployment Admin"
  # smtp_mail:
  #   host:
  #   port: 587
  #   encryption: tls
  #   username:
  #   password
  #   password_secret:
  #     name:
  #     key:
  # mailgun_mail:
  #   domain:
  #   secret:
  #   secret_ref:
  #     name:
  #     key:
  ##
  ## Additional settings provided in .env file, note that this only works for
  ## versions after commit
  ## https://github.com/ushahidi/platform/pull/3986/commits/2e03a09e3e8c4731b2f0ad3298806363c6d076d8
  # dotenv: ""
  ## Same as above, but coming from a secret
  # dotenv_secret:
  #   name:
  #   key:
  ## Secret containing keys oauth-public.key and oauth-private.key for passport
  # passport_keys_secret:

api:
  replicas: 1
  debug: "False"
  params:
    php_exec_time_limit: 60
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"
  # deployment:
  #   annotations:
  ingress:
    enabled: false
    # annotations:
    # tls:
    # - secretName: domain.example.com
    #   hosts:
    #   - domain.example.com
    host: # domain.example.com

worker:
  replicas: 1
  debug: "False"
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"
  # deployment:
  #   annotations:

crond:
  ### replicas: 1  --> this is not observed, there must always be just 1 crond
  debug: "False"
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"
  # deployment:
  #   annotations:

# This provides a compatible mysql server, with EPHEMERAL storage.
# Don't rely on it for production.
mysql:
  ## Set to false to disable
  enabled: true
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: 8Gi
    # storageClass:
    # existingClaim:
    annotations: {}
    labels: {}
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"

# This provides a compatible redis server, with EPHEMERAL storage.
# Don't rely on it for production.
redis:
  ## Set to false to disable
  enabled: true
  limits:
    cpu: "1"
    memory: "1Gi"
  requests:
    cpu: "10m"
    memory: "64Mi"
